; Configuración de PHP para el contenedor.
memory_limit = 512M
upload_max_filesize = 20M
post_max_size = 120M
max_execution_time = 300
max_input_time = 300
max_file_uploads = 60
date.timezone = America/Bogota

opcache.enable = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
